name: deploy

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'image_tag'
        default: 'latest'
        required: true
        type: string

  push:
    # branches:
    #   - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  push2registry:
    name: Push container to GHCR registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Docker build
        if: ${{ github.ref_type != 'tag' }}
        run: docker build -t ghcr.io/gjovani-vega/docker-nodejs-sample:${{ github.event.inputs.image_tag }} .
      
      - name: Docker build
        if: ${{ github.ref_type == 'tag' }}
        run: docker build -t ghcr.io/gjovani-vega/docker-nodejs-sample:${{ github.ref_name }} .

      - name: Login to GitHub CR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: gjovani-vega
          password: ${{ secrets.GH_TOKEN }}

      - name: Push container
        if: ${{ github.ref_type != 'tag' }}
        run: docker push ghcr.io/gjovani-vega/docker-nodejs-sample:${{ github.event.inputs.image_tag }}
      
      - name: Push container 
        if: ${{ github.ref_type == 'tag' }}
        run: docker push ghcr.io/gjovani-vega/docker-nodejs-sample:${{ github.ref_name }}